version: '3.7'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./.aws:/root/.aws
      - ./app:/app